include $(AMF_PROJECT_MK_ROOT)/rule.mk

MODULE_BEFORE=before
MODULE_AFTER=end

before:
	@echo "do something before make"

end:
	@echo "do something after make"

TARGET_TYPE=bin
SUB_MODULE=
INCLUDE_PATH+=
TARGET_NAME=test
include $(AMF_PROJECT_MK_ROOT)/basic.mk

