include $(AMF_PROJECT_MK_ROOT)/rule.mk

TARGET_TYPE=obj
TARGET_NAME=syntax

#ld 选项
LD_FLAGS+=-lxml

#c_complier flags
C_COMPLIER_FLAGS+= -I../plugin/ -I../ -I../debug/

include $(AMF_PROJECT_MK_ROOT)/basic.mk

