
#coding:utf-8
from release.cfg import config_base

global_cfg=None

def get_cfg_manager():
    global global_cfg
    if global_cfg:
        return global_cfg
    cfg=config_base.ConfigManager()
    cfg.add_config([
        {'segment':'source',
         'config_name':'url',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出源码路径,例如 svn://192.168.0.1/svnroot/project1',
         'config_param':None
        },
        {'segment':'source',
         'config_name':'type',
         'config_type':'enum',
         'default_value':"svn",
         'helper':'此选项用于指出源码插件类型',
         'config_param':['svn']
        },
        {'segment':'source',
         'config_name':'username',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出源码下载用户名',
         'config_param':None
        },
        {'segment':'source',
         'config_name':'password',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出源码源码下载用户对应地密码',
         'config_param':None
        },
        {'segment':'build',
         'config_name':'host',
         'config_type':'string',
         'default_value':"127.0.0.1",
         'helper':'此选项用于指出编译机器主机ip',
         'config_param':None
        },
        {'segment':'build',
         'config_name':'workspace-dir',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出编译开始时工作目录',
         'config_param':None
        },
        {'segment':'build',
         'config_name':'username',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出编译机器用户名',
         'config_param':None
        },
        {'segment':'build',
         'config_name':'password',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出编译机器密码',
         'config_param':None
        },
        {'segment':'build',
         'config_name':'build-script',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于编译脚本',
         'config_param':None
        },
        {'segment':'collect',
         'config_name':'target',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出发布文件名称',
         'config_param':None
        },
        {'segment':'collect',
         'config_name':'target-host',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出发布机器ip',
         'config_param':None
        },
        {'segment':'collect',
         'config_name':'username',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出发布机器用户名',
         'config_param':None
        },
        {'segment':'collect',
         'config_name':'password',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出发布机器密码',
         'config_param':None
        },
        {'segment':'collect',
         'config_name':'collect-script',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出发布文件脚本',
         'config_param':None
        },
        {'segment':'monitor',
         'config_name':'interval',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出源码变更检测周期时间(单位S)',
         'config_param':None
        },
        {'segment':'monitor',
         'config_name':'log',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出系统日志存放位置',
         'config_param':None
        },
        {'segment':'monitor',
         'config_name':'result-mail-to',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出结果通知人员邮箱地址',
         'config_param':None
        },
        {'segment':'monitor',
         'config_name':'smtp-addr',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出邮件传输服务器地址,例如stmp.126.com',
         'config_param':None
        },
        {'segment':'monitor',
         'config_name':'smtp-port',
         'config_type':'int',
         'default_value':994,
         'helper':'此选项用于指出smtp报务器端口号',
         'config_param':None
        },
         {'segment':'monitor',
         'config_name':'sender-mail-name',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出发件人地址',
         'config_param':None
        },
         {'segment':'monitor',
         'config_name':'sender-mail-password',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出发件人密码',
         'config_param':None
        },
         {'segment':'monitor',
         'config_name':'release-fail',
         'config_type':'enum',
         'default_value':"ignore",
         'helper':'此选项用于出错时处理方式',
         'config_param':["ignore","prev-version","next-version"]
        },
         {'segment':'event',
         'config_name':'release-server-setup',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于服务启动时事件',
         'config_param':None
        },
         {'segment':'event',
         'config_name':'release-begin',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出每个服务周期开启时事件',
         'config_param':None
        },
         {'segment':'event',
         'config_name':'source-checkout-before',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出导出源码前事件',
         'config_param':None
        },
         {'segment':'event',
         'config_name':'source-checkout-after',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出导出源码后事件',
         'config_param':None
        },
         {'segment':'event',
         'config_name':'source-build-before',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出构造前事件',
         'config_param':None
        },
         {'segment':'event',
         'config_name':'source-build-after',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出构造后事件',
         'config_param':None
        },
         {'segment':'event',
         'config_name':'result-collect-before',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出发布收集前事件',
         'config_param':None
        },
         {'segment':'event',
         'config_name':'result-collect-after',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出发布收集后事件',
         'config_param':None
        },
        {'segment':'event',
         'config_name':'result-package-before',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出打包前事件',
         'config_param':None
        },
        {'segment':'event',
         'config_name':'result-package-after',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出打包后事件',
         'config_param':None
        },
        {'segment':'event',
         'config_name':'release-finish',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出发布后事件',
         'config_param':None
        },
        {'segment':'event',
         'config_name':'release-server-stop',
         'config_type':'string',
         'default_value':"",
         'helper':'此选项用于指出服务停机事件',
         'config_param':None
        },
    ])

    global_cfg=cfg
    return global_cfg
