include $(AMF_PROJECT_MK_ROOT)/rule.mk

CPLUS_SRCS= tinystr.cpp tinyxml.cpp tinyxmlerror.cpp tinyxmlparser.cpp #xmltest.cpp
TARGET_TYPE=obj
TARGET_NAME=tinyxml

CPLUS_COMPLIER_FLAGS+= -fPIC
include $(AMF_PROJECT_MK_ROOT)/basic.mk
