#! /bin/bash

#awk -F'>' -f index.awk an.txt
#awk -f info.awk  an.txt   >cn.txt

source content 

#HOME_INFO_URL='http://www.fang99.com/buycenter/buildInfo.aspx?BuildingId=0000001132'
#helper_get_page_content "$HOME_INFO_URL" | tr -d '\r\n' | sed 's.</\?tr>.\n.g;s.</td>.\n.g;s.<td.\n<td.g;' | grep "<td" | sed -n '175p;60p;117p;101p;103p;105p;97p;48p;157p;159p;161p;163p;177p;179p;123p;125p;127p;129p;131p;133p;135p;89p;36p'

cat cn.txt | awk -F'>' -f info.awk
